[build]
  command = "npm build"
  publish = "dist"

[dev]
  command = "npm dev"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Content-Security-Policy = "default-src 'self' data: 'unsafe-inline' cdn.jsdelivr.net gc.zgo.at jfranciscosousa.goatcounter.com unpkg.com fonts.googleapis.com fonts.gstatic.com"
    X-XSS-Protection = "1"
