allowBuilds:
  "@swc/core": true
  esbuild: true
  puppeteer: true
  sharp: true
autoInstallPeers: false
minimumReleaseAge: 7200

onlyBuiltDependencies:
  - "@swc/core"
  - "@tailwindcss/oxide"
  - esbuild
  - sharp
