name: Weekly Netlify Deploy

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Node CI
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v1.2.0

      - name: Cache node modules
        uses: actions/cache@v2
        with:
            path: |
              ~/.pnpm-store
              node_modules
            key: ${{ runner.os }}-build-node_modules-${{ hashFiles('**/pnpm-lock.yaml') }}
            restore-keys: |
              ${{ runner.os }}-build-node_modules-
              ${{ runner.os }}-build-
              ${{ runner.os }}-

      - name: Build website
        run: pnpm install && pnpm build
        env:
            GOODREADS_API_KEY: ${{ secrets.GOODREADS_API_KEY }}

      - name: Upload to netlify
        uses: netlify/actions/cli@master
        with:
            args: deploy --prod
        env:
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
